// src/rendering/materialTileFiles.ts

// Mappa: materiale → lista di file delle tiles da caricare
export const MATERIAL_TILE_FILES: Record<string, string[]> = {
  dirt: [
    "/tiles/dirt/dirt_stylized_rock_1.png",
    "/tiles/dirt/dirt_stylized_rock_2.png",
    "/tiles/dirt/dirt_stylized_rock_3.png",
    "/tiles/dirt/dirt_stylized_rock_4.png",
    "/tiles/dirt/dirt_stylized_rock_5.png",
    "/tiles/dirt/dirt_stylized_rock_6.png",
    "/tiles/dirt/dirt_stylized_rock_7.png",
    "/tiles/dirt/dirt_stylized_rock_8.png",
    "/tiles/dirt/dirt_stylized_rock_9.png",
    "/tiles/dirt/dirt_stylized_rock_10.png",
    "/tiles/dirt/dirt_stylized_rock_11.png",
    "/tiles/dirt/dirt_stylized_rock_12.png",
    "/tiles/dirt/dirt_stylized_rock_13.png",
    "/tiles/dirt/dirt_stylized_rock_14.png",
    "/tiles/dirt/dirt_stylized_rock_15.png",
  ],

  grass: [
    "/tiles/grass/grass_1.png",
    "/tiles/grass/grass_2.png",
    "/tiles/grass/grass_3.png",
    "/tiles/grass/grass_4.png",
    "/tiles/grass/grass_5.png",
    "/tiles/grass/grass_6.png",
    "/tiles/grass/grass_7.png",
    "/tiles/grass/grass_8.png",
    "/tiles/grass/grass_9.png",
    "/tiles/grass/grass_10.png",
    "/tiles/grass/grass_11.png",
    "/tiles/grass/grass_12.png",
    "/tiles/grass/grass_13.png",
    "/tiles/grass/grass_14.png",
    "/tiles/grass/grass_15.png",
  ],

  water: [
    "/tiles/water/water_1.png",
    "/tiles/water/water_2.png",
    "/tiles/water/water_3.png",
    "/tiles/water/water_4.png",
    "/tiles/water/water_5.png",
    "/tiles/water/water_6.png",
    "/tiles/water/water_7.png",
    "/tiles/water/water_8.png",
    "/tiles/water/water_9.png",
    "/tiles/water/water_10.png",
    "/tiles/water/water_11.png",
    "/tiles/water/water_12.png",
    "/tiles/water/water_13.png",
    "/tiles/water/water_14.png",
    "/tiles/water/water_15.png",
  ],

  reddungeon: [
    "/tiles/reddungeon/reddungeon_1.png",
    "/tiles/reddungeon/reddungeon_2.png",
    "/tiles/reddungeon/reddungeon_3.png",
    "/tiles/reddungeon/reddungeon_4.png",
    "/tiles/reddungeon/reddungeon_5.png",
    "/tiles/reddungeon/reddungeon_6.png",
    "/tiles/reddungeon/reddungeon_7.png",
    "/tiles/reddungeon/reddungeon_8.png",
    "/tiles/reddungeon/reddungeon_9.png",
    "/tiles/reddungeon/reddungeon_10.png",
    "/tiles/reddungeon/reddungeon_11.png",
    "/tiles/reddungeon/reddungeon_12.png",
    "/tiles/reddungeon/reddungeon_13.png",
    "/tiles/reddungeon/reddungeon_14.png",
    "/tiles/reddungeon/reddungeon_15.png",
  ],
};
